development: 
  adapter: postgresql
  encoding: utf8
  database: find_a_farm_development
  pool: 5

test: 
  adapter: postgresql 
  encoding: utf8 
  reconnect: false 
  database: find_a_farm_test 
  pool: 5